### PR TITLE
fix: remove outdated table of cfeps

### PR DESCRIPTION
**Pull request by beckermr**
This PR cleans up some old cruft.

### CODE REVIEW

**Comment by beckermr** [comment]
ready to merge @conda-forge/core

**Comment by xhochy** [comment]
I really like this table and frequently click on these links as numbers in filenames are not that intuitive. Should I instead update it?

**Comment by beckermr** [comment]
IMHO we should write code to automatically generate it or remove it.

**Comment by jaimergp** [comment]
FYI, we automatically populate this list in https://conda-forge.org/community/cfep/. Maybe a link in this section is sufficient? If you prefer that list to be a table, that's a simple change too @xhochy

**Comment by beckermr** [comment]
I am going to close this for now, since we do not plan to merge. We can either update or replace with a link in another PR.

**Pull request closed without merging**
