### PR TITLE
Propose to extend clep'05 labels also to Long Term Releases

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
What does ltr mean in this case? What should users expect when installing from that channel? What kind of support should the maintainers provide? For example are `ltr` labeled packages getting rebuilds of their pinned dependencies?

Edit: respect -> expect typo, sorry

**Comment by SrNetoChan** [comment]
> What does ltr mean in this case? What should users respect when installing from that channel? What kind of support should the maintainers provide? For example are `ltr` labeled packages getting rebuilds of their pinned dependencies?

@CJ-Wright  ltr means long term release. I should have presented my use case: QGIS

In QGIS, we have a normal stable release (3.18 now) and a LTR (3.16 now). They are both stable, but in each 4 stable releases, one becomes an LTR. During an year, the LTR branch only receives fixes and improvements, no new features are allowed.

I maintain a LTR branch on QGIS-feedsock, brasically I just make sure to update the new version and the hash. I also pin a few dependencies so that updates don't risk to break peoples workflows. 

Currently, for the LTR, we teach people to force the QGIS version during the installation. With a label, they could install the LTR without the need to knowing which is the version of the current LTR.

**Comment by CJ-Wright** [comment]
Hmm. I guess my questions are more aimed at what does a long term release mean in the context of conda-forge. This isn't so much an issue with dev/rc labels since they are mostly unsupported, in the sense that if something broke or they weren't rebuilt with the latest global pin it would be fine. My understanding here is that it would be quite different, LTR releases are expected to be supported. Mostly I'm trying to get at if LTR labeled packages have particular expectations attached to them from the conda-forge side, ie rebuilds. If they do, what are they and do we need to make certain they are met?

**Comment by SrNetoChan** [comment]
> Hmm. I guess my questions are more aimed at what does a long term release mean in the context of conda-forge. This isn't so much an issue with dev/rc labels since they are mostly unsupported, in the sense that if something broke or they weren't rebuilt with the latest global pin it would be fine. My understanding here is that it would be quite different, LTR releases are expected to be supported. Mostly I'm trying to get at if LTR labeled packages have particular expectations attached to them from the conda-forge side, ie rebuilds. If they do, what are they and do we need to make certain they are met?

@CJ-Wright, at least for QGIS, the ltr expectations are more or less the same as of the main branch. The reason to maintain an LTR is to have a more stable version available. This is the version the QGIS project suggests for organizations to use in production, that's why I try to keep it available.

Every month there's a new patch release, and I try to get it rebuilt. If something goes wrong, normally I get support from @ocefpaf  or Sam Gillingham. I don't expect any extra involvement from conda-forge like automatic rebuild. I took that task to myself.

I have no idea if there other packages that would benefit or already releasing parallel versions.

**Comment by isuruf** [comment]
Why not have a `qgis-ltr` conda meta package?

**Comment by SrNetoChan** [comment]
@isuruf Sorry, I am not sure how that works.  would that mean a new feedstock? For me, all options are valid. Even keeping the way it is :-) Just want to make it in a way that makes sense for the rest of the conda-forge community.

**Comment by chrisburr** [comment]
The simplest would be to make the lts branch in the feedstock produce multiple outputs, similar to how `matplotlib` is a metapackage around `matplotlib-base`: https://github.com/conda-forge/matplotlib-feedstock/blob/1fb8f9baf8b74041daf9a84a115d00653c9e1cab/recipe/meta.yaml#L75-L87

**Comment by SrNetoChan** [comment]
> The simplest would be to make the lts branch in the feedstock produce multiple outputs, similar to how `matplotlib` is a metapackage around `matplotlib-base`: https://github.com/conda-forge/matplotlib-feedstock/blob/1fb8f9baf8b74041daf9a84a115d00653c9e1cab/recipe/meta.yaml#L75-L87

Seems that this is the preferable approach. I will close this ticket and investigate what you propose. Thank you all for your inputs.

**Pull request closed without merging**
